[{
		name: "皇室幽灵",
		src: 1,
		arena: "部队",
		rarity：: "传说",
		holyWater: "3",
		attackSpeed: "1.7",
		aims: "地面目标",
		movingSpeed: "快",
		attackDistance: "近战",
		waitTime: "1秒",
		introduce: "一个在竞技场中游荡的隐形幽灵，当他被敌人惊醒后，便会显形并发动攻击！",
		getWay: "10阶竞技场解锁"
	},
	{
		name: "电击车小队",
		src: 2,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "4",
		attackSpeed: "1.6",
		aims: "地面目标",
		movingSpeed: "中等",
		attackDistance: "4.5",
		waitTime: "1秒",
		introduce: "三台微型电击车，究竟是谁在操控它们......？？恐怕只有建筑大师知道。",
		getWay: "11阶竞技场解锁"
	},
	{
		name: "猎人",
		src: 3,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "4",
		attackSpeed: "2.2",
		aims: "陆空兼顾",
		movingSpeed: "中等",
		attackDistance: "6.5",
		waitTime: "1秒",
		introduce: "他能对近距离目标造成大量伤害，但对付远距离目标时效果略逊一筹。",
		getWay: "9阶竞技场解锁"
	},
	{
		name: "飞行器",
		src: 4,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "4",
		attackSpeed: "1秒",
		aims: "陆空兼顾",
		movingSpeed: "快",
		attackDistance: "6",
		waitTime: "1秒",
		introduce: "一个速度很快的空中飞行器，虽然脆皮但效果拔群",
		getWay: "暂无"
	},
	{
		name: "超级骑士",
		src: 5,
		arena: "部队",
		rarity：: "传说",
		holyWater: "7",
		attackSpeed: "1.8",
		aims: "地面目标",
		movingSpeed: "中等",
		attackDistance: "4-5",
		waitTime: "1秒",
		introduce: "具有登场攻击特效，拥有独特跃击属性，对地范围伤害，无法对空",
		getWay: "10阶竞技场解锁 【超级骑士卡组推荐】 【超级骑士实战视频】"
	},
	{
		name: "骷髅气球",
		src: 6,
		arena: "部队",
		rarity：: "普通",
		holyWater: "3",
		movingSpeed: "中等",
		waitTime: "1秒",
		amount: "8",
		introduce: "气球被击破后地面产生8只骷髅兵",
		getWay: "暂无"
	},
	{
		name: "加农炮战车",
		src: 7,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "5",
		attackSpeed: "1.2秒",
		aims: "地面目标",
		movingSpeed: "快",
		attackDistance: "5.5",
		waitTime: "1秒",
		introduce: "带轮子的加农炮，跑步生风，开车开车！",
		getWay: "暂无 【加农炮战车卡组推荐】 【加农炮战车实战视频】"
	},
	{
		name: "暗夜女巫",
		src: 8,
		arena: "部队",
		rarity：: "传说",
		holyWater: "4",
		attackSpeed: "1.5s",
		aims: "地面目标",
		movingSpeed: "中等",
		attackDistance: "近战",
		waitTime: "1s",
		introduce: "每6秒产生2只蝙蝠 死亡后产生3只蝙蝠",
		getWay: "8阶宝箱、传奇商店购买、传奇宝箱 【暗夜女巫卡组推荐】 【暗夜女巫卡组搭配视频】"
	},
	{
		name: "治疗法术",
		src: 9,
		arena: "法术",
		rarity：: "稀有",
		holyWater: "3",
		持续时间：: "3s",
		introduce: "每秒治疗一定的血量",
		getWay: "10阶竞技场宝箱、商店购买"
	},
	{
		name: "蝙蝠",
		src: 10,
		arena: "部队",
		rarity：: "普通",
		holyWater: "2",
		attackSpeed: "1s",
		aims: "陆空兼顾",
		movingSpeed: "非常快",
		attackDistance: "近战",
		amount: "5",
		introduce: "召唤出4只蝙蝠，移动速度快，血量和攻击与小骷髅一样",
		getWay: "商店购买、8阶宝箱"
	},
	{
		name: "幻影刺客",
		src: 11,
		arena: "部队",
		rarity：: "传说",
		holyWater: "3",
		attackSpeed: "1",
		movingSpeed: "快速",
		attackDistance: "近战",
		amount: "1",
		introduce: "具有突袭的效果，对突袭的目标产生双倍伤害。不过她无法对在4格以内的单位进行突袭！",
		getWay: "传奇宝箱、9阶宝箱、传奇商店购买"
	},
	{
		name: "哥布林团伙",
		src: 12,
		arena: "部队",
		rarity：: "普通",
		holyWater: "3",
		aims: "陆空兼顾",
		movingSpeed: "非常快",
		amount: "5",
		introduce: "同时召唤出3个哥布林和2个哥布林投手，可以说相当强大！",
		getWay: "9阶宝箱、商店购买、部落捐赠"
	},
	{
		name: "野蛮人攻城锤",
		src: 13,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "4",
		aims: "建筑",
		movingSpeed: "中等",
		attackDistance: "近战",
		introduce: "4费的部队卡，有冲锋效果去攻击建筑物，在木锤毁灭之后出现2个野蛮人。",
		getWay: "6阶宝箱、商店购买、部落捐赠"
	},
	{
		name: "吹箭哥布林",
		src: 14,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "3",
		attackSpeed: "0.7s",
		aims: "陆空兼顾",
		movingSpeed: "非常快",
		attackDistance: "6.5",
		amount: "1",
		introduce: "远程射击，伤害可以说跟火枪手不相上下，但是血量上会稍微逊色于火枪手。",
		getWay: "9阶宝箱、9阶商店、部落捐赠"
	},
	{
		name: "飞斧屠夫",
		src: 15,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "5",
		attackSpeed: "2.4s",
		aims: "陆空兼顾",
		movingSpeed: "中等",
		attackDistance: "5",
		waitTime: "1s",
		introduce: "效果就是投掷一把斧头出去，然后斧头又回到了手上，不就是回旋斧嘛!",
		getWay: "9阶宝箱、9阶商店、周末紫卡捐赠"
	},
	{
		name: "闪电法师",
		src: 16,
		arena: "部队",
		rarity：: "传说",
		holyWater: "5",
		attackSpeed: "1.8",
		aims: "陆空兼顾",
		movingSpeed: "快",
		attackDistance: "5",
		waitTime: "1s",
		introduce: "4费的部队卡，攻击效果具有晕眩效果",
		getWay: "7阶竞技场宝箱、9阶商店获得、传奇宝箱"
	},
	{
		name: "克隆法术",
		src: 17,
		arena: "法术",
		rarity：: "史诗",
		holyWater: "3",
		introduce: "可以将区域内的友军进行克隆复制，但是生命值非常的低，但是攻击力却是一样的，并且对建筑无效！",
		getWay: "8阶宝箱、商店购买"
	},
	{
		name: "野蛮人精锐",
		src: 18,
		arena: "部队",
		rarity：: "普通",
		holyWater: "6",
		attackSpeed: "1.5",
		aims: "地面目标",
		movingSpeed: "极快",
		waitTime: "1s",
		amount: "2",
		introduce: "6费的部队卡，你可以把他看成是血量加强版的野蛮人，攻击力、血量、移动速度都高于野蛮人。",
		getWay: "7阶竞技场、宝箱获得、部落捐赠"
	},
	{
		name: "飓风法术",
		src: 19,
		arena: "法术",
		rarity：: "史诗",
		holyWater: "3",
		aims: "地面目标",
		attackDistance: "5格",
		持续时间：: "2.5s",
		introduce: "将敌人线路上的敌人都卷到龙卷风里面，持续2.5s，并且造成小量伤害！",
		getWay: "宝箱获得、商店购买"
	},
	{
		name: "骷髅召唤",
		src: 20,
		arena: "法术",
		rarity：: "传说",
		holyWater: "5",
		aims: "地面目标",
		持续时间：: "10s",
		生产速度：: "0.5s",
		introduce: "在施法区域召唤骷髅，0.5秒召唤一只，持续10秒，一共20只。",
		getWay: "通过宝箱获得、A9商店金币购买"
	},
	{
		name: "戈仑冰人",
		src: 21,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "2",
		attackSpeed: "2.3s",
		aims: "建筑",
		movingSpeed: "慢",
		attackDistance: "近战",
		waitTime: "1s",
		introduce: "在死后能对周围的单位产生减速效果",
		getWay: "8阶竞技场宝箱、商店购买"
	},
	{
		name: "地狱飞龙",
		src: 22,
		arena: "部队",
		rarity：: "传说",
		holyWater: "4",
		attackSpeed: "0.4秒",
		aims: "陆空兼顾",
		movingSpeed: "中等",
		attackDistance: "4",
		waitTime: "1秒",
		introduce: "地狱飞龙对单个目标喷射火焰射线，伤害随着时间递增。",
		getWay: "4阶竞技场，商店"
	},
	{
		name: "重甲亡灵",
		src: 23,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "3",
		attackSpeed: "1.3sec",
		movingSpeed: "中等",
		attackDistance: "2",
		waitTime: "1sec",
		amount: "1",
		introduce: "可对空可对地的空中部队，对抗单体部队有着不错的优势",
		getWay: "7阶竞技场，商店"
	},
	{
		name: "复仇滚木",
		src: 24,
		arena: "法术",
		rarity：: "传说",
		holyWater: "2",
		aims: "地面目标",
		作用范围：: "11.1",
		introduce: "召唤出一个长条滚木，在经过的路程中对部队造成伤害，并有击退效果。",
		getWay: "A9传奇商店购买、宝箱"
	},
	{
		name: "寒冰精灵",
		src: 25,
		arena: "部队",
		rarity：: "普通",
		holyWater: "1",
		aims: "陆空兼顾",
		movingSpeed: "非常快",
		attackDistance: "2.5格",
		waitTime: "1s",
		amount: "1",
		introduce: "产生1个会造成冰冻效果的寒冰精灵,对敌方部队造成2秒冰冻。",
		getWay: "A8竞技场解锁、宝箱、商店购买"
	},
	{
		name: "狂暴樵夫",
		src: 26,
		arena: "部队",
		rarity：: "传说",
		holyWater: "4",
		attackSpeed: "1.1s",
		aims: "地面目标",
		movingSpeed: "快",
		waitTime: "1s",
		amount: "1",
		introduce: "狂暴樵夫在死后会丢下一个狂暴效果，在范围内具有狂暴效果。",
		getWay: "A9商店购买、宝箱"
	},
	{
		name: "巨石投手",
		src: 27,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "6",
		attackSpeed: "2.5s",
		aims: "地面目标",
		movingSpeed: "慢",
		attackDistance: "5",
		waitTime: "1",
		introduce: "召唤一个巨石投手，使用巨石砸向对面的部队，并且附带击退效果。",
		getWay: "A8竞技场、宝箱、商店"
	},
	{
		name: "烈焰熔炉",
		src: 28,
		arena: "建筑",
		rarity：: "稀有",
		holyWater: "4",
		waitTime: "1秒",
		soldierSpeed: "10秒",
		持续时间：: "50秒",
		introduce: "定时召唤2只会自爆的烈焰精灵",
		getWay: "5阶竞技场，商店，部落捐赠"
	},
	{
		name: "骷髅守卫",
		src: 29,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "3",
		attackSpeed: "1.2s",
		movingSpeed: "快",
		attackDistance: "近战",
		waitTime: "1s",
		amount: "X3",
		introduce: "和黑骑士一样具有护盾效果，可以避免被1下戳死！",
		getWay: "7阶竞技场、宝箱、商店购买"
	},
	{
		name: "烈焰精灵",
		src: 30,
		arena: "部队",
		rarity：: "普通",
		holyWater: "2",
		aims: "陆空兼顾",
		movingSpeed: "极快",
		attackDistance: "2",
		waitTime: "1秒",
		amount: "X3",
		introduce: "产生3个会自爆的烈焰精灵。",
		getWay: "5阶竞技场，部落捐赠，商店"
	},
	{
		name: "电磁炮",
		src: 31,
		arena: "部队",
		rarity：: "传说",
		holyWater: "6",
		attackSpeed: "5秒",
		aims: "地面目标",
		movingSpeed: "慢",
		attackDistance: "4.5",
		waitTime: "1秒",
		introduce: "电磁炮是一个移动炮塔，5秒打一炮，伤害超级高！",
		getWay: "6阶竞技场，8阶商店"
	},
	{
		name: "掘地矿工",
		src: 32,
		arena: "部队",
		rarity：: "传说",
		holyWater: "3",
		attackSpeed: "1.2秒",
		aims: "地面目标",
		movingSpeed: "快",
		attackDistance: "近战",
		waitTime: "1秒",
		introduce: "召唤一只能挖地道的矿工，他可以快速的到达场上的任何位置",
		getWay: "6阶竞技场，8阶商店"
	},
	{
		name: "熔岩猎犬",
		src: 33,
		arena: "部队",
		rarity：: "传说",
		holyWater: "7",
		attackSpeed: "1.3秒",
		aims: "建筑",
		movingSpeed: "慢",
		attackDistance: "2",
		waitTime: "1秒",
		introduce: "血厚，移动速度慢，死后会产出6只小狗。",
		getWay: "4阶竞技场，8阶商店。"
	},
	{
		name: "巨人",
		src: 34,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "5",
		attackSpeed: "1.5s",
		aims: "建筑",
		movingSpeed: "慢",
		waitTime: "1s",
		introduce: "巨人行动缓慢，但是耐击打。他专门攻击建筑，是名副其实的人肉攻城器！",
		getWay: "新手训练营、商店购买、部落捐赠"
	},
	{
		name: "气球兵",
		src: 35,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "5",
		attackSpeed: "3秒",
		aims: "建筑",
		movingSpeed: "中等",
		attackDistance: "近战",
		waitTime: "1秒",
		introduce: "召唤出一个近战哥布林气球，气球以塔和建筑物为攻击目标，向地面扔炸弹造成范围伤害。",
		getWay: "2阶竞技场，商店"
	},
	{
		name: "皮卡超人",
		src: 36,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "7",
		attackSpeed: "1.8秒",
		aims: "地面目标",
		movingSpeed: "慢",
		attackDistance: "近战",
		waitTime: "3秒",
		introduce: "召唤出一个近战大皮卡，大皮卡移动缓慢但攻击力极高。",
		getWay: "4阶竞技场，商店"
	},
	{
		name: "火枪手",
		src: 37,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "4",
		attackSpeed: "1.1s",
		aims: "陆空兼顾",
		movingSpeed: "中等",
		attackDistance: "6.5",
		waitTime: "1s",
		introduce: "召唤一个超远程的火枪手，别被她优雅的外表迷惑了，火枪手一拿起武器可是毫不留情！",
		getWay: "新手训练营、商店购买、部落捐赠"
	},
	{
		name: "女巫",
		src: 38,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "5",
		attackSpeed: "0.7s",
		aims: "陆空兼顾",
		movingSpeed: "中等",
		attackDistance: "6.0",
		waitTime: "1s",
		introduce: "召唤出一个女巫，女巫能每7s召唤小骷髅，并且攻击属于AOE伤害。",
		getWay: "新手训练营、商店购买"
	},
	{
		name: "迷你皮卡",
		src: 39,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "4",
		attackSpeed: "1.8s",
		aims: "地面目标",
		movingSpeed: "快",
		waitTime: "1s",
		introduce: "召唤出一个近战的迷你皮卡，单体攻击力非常高",
		getWay: "新手训练营、商店购买、部落捐赠"
	},
	{
		name: "法师",
		src: 40,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "5",
		attackSpeed: "1.4秒",
		aims: "陆空兼顾",
		movingSpeed: "中等",
		attackDistance: "5.5",
		waitTime: "1",
		introduce: "有史以来竞技场中最令人生畏的人，法师单靠着他的英俊或火球就能把你击飞。",
		getWay: "5阶竞技场，部落捐赠，商店购买"
	},
	{
		name: "飞龙宝宝",
		src: 41,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "4",
		attackSpeed: "1.8秒",
		aims: "陆空兼顾",
		movingSpeed: "快",
		attackDistance: "3.5",
		waitTime: "1秒",
		introduce: "可造成范围伤害的飞行单位。可爱又贪吃的飞龙宝宝已经准备好迎接烤肉大餐啦！",
		getWay: "新手训练营，商店，"
	},
	{
		name: "王子",
		src: 42,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "5",
		attackSpeed: "1.5s",
		aims: "地面目标",
		movingSpeed: "中等",
		waitTime: "1s",
		introduce: "不要被这匹小马糊弄了。一旦王子的马奔跑起来，你就等着被践踏吧。他冲锋时会造成双倍伤害。",
		getWay: "新手训练营、商店购买"
	},
	{
		name: "骷髅巨人",
		src: 43,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "6",
		attackSpeed: "1.5秒",
		aims: "地面目标",
		movingSpeed: "中",
		attackDistance: "近战",
		waitTime: "1秒",
		introduce: "召唤出一个骷髅巨人，骷髅巨人被消灭后，会在原地大范围爆炸并造成极高伤害。",
		getWay: "2阶竞技场，商店"
	},
	{
		name: "野猪骑士",
		src: 44,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "4",
		attackSpeed: "1.5秒",
		aims: "建筑",
		movingSpeed: "非常快",
		attackDistance: "近战",
		waitTime: "1秒",
		introduce: "召唤出一个移动速度快的野猪骑士，野猪骑士能够跨越河流，但是只会以建筑为攻击目标。",
		getWay: "4阶竞技场，商店，部落捐赠"
	},
	{
		name: "毒药法术",
		src: 45,
		arena: "法术",
		rarity：: "史诗",
		holyWater: "4",
		作用范围：: "3.5",
		持续时间：: "10秒",
		introduce: "用黏黏的毒素覆盖目标区域，对其中的部队和建筑造成伤害并减速。",
		getWay: "5阶竞技场、商店"
	},
	{
		name: "公主",
		src: 46,
		arena: "部队",
		rarity：: "传说",
		holyWater: "3",
		attackSpeed: "3秒",
		aims: "陆空兼顾",
		movingSpeed: "中等",
		attackDistance: "9.5",
		waitTime: "1秒",
		introduce: "召唤公主出来帮忙，能够射出一串穿过一半竞技场距离的燃烧箭。",
		getWay: "7阶竞技场解锁"
	},
	{
		name: "寒冰法师",
		src: 47,
		arena: "部队",
		rarity：: "传说",
		holyWater: "3",
		attackSpeed: "1.5秒",
		aims: "陆空兼顾",
		movingSpeed: "中等",
		attackDistance: "6",
		waitTime: "1",
		introduce: "召唤冰法师出来帮忙，冰法师的攻击能够削减敌人的移动速度和攻击速度。",
		getWay: "5阶竞技场"
	},
	{
		name: "三个火枪手",
		src: 48,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "9",
		attackSpeed: "1.1秒",
		aims: "陆空兼顾",
		movingSpeed: "中等",
		attackDistance: "6.5",
		waitTime: "1秒",
		introduce: "召唤出三个远程攻击的火枪手。",
		getWay: "7阶竞技场解锁、部落捐兵、商店随机刷新"
	},
	{
		name: "黑暗王子",
		src: 49,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "4",
		attackSpeed: "1.5秒",
		aims: "地面目标",
		movingSpeed: "中等",
		attackDistance: "近战",
		waitTime: "1秒",
		introduce: "黑暗王子能够造成范围伤害，而且冲锋过后伤害会翻倍。要想伤害黑暗王子，还得先破坏掉他身上的盾。",
		getWay: "7阶竞技场解锁、商店随机刷新"
	},
	{
		name: "皇家巨人",
		src: 50,
		arena: "部队",
		rarity：: "普通",
		holyWater: "6",
		attackSpeed: "1.5秒",
		aims: "建筑",
		movingSpeed: "慢",
		attackDistance: "7",
		waitTime: "2秒",
		introduce: "召唤一个远程攻击的皇家巨人，皇家巨人只会以建筑为目标。",
		getWay: "7阶竞技场解锁、商店随机刷新、部落捐卡"
	},
	{
		name: "骷髅军团",
		src: 51,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "3",
		waitTime: "1s",
		amount: "14个",
		introduce: "召唤出一个数量为20的近战骷髅小部队。",
		getWay: "新手训练营，商店购买。"
	},
	{
		name: "冰冻法术",
		src: 52,
		arena: "法术",
		rarity：: "史诗",
		holyWater: "4",
		作用范围：: "3",
		持续时间：: "5秒",
		introduce: "冰冻敌军和建筑，使它们无法移动或攻击。",
		getWay: "4阶竞技场，商店"
	},
	{
		name: "地狱塔",
		src: 53,
		arena: "建筑",
		rarity：: "稀有",
		holyWater: "5",
		attackSpeed: "0.4秒",
		aims: "陆空兼顾",
		attackDistance: "6.5",
		waitTime: "1秒",
		持续时间：: "40秒",
		introduce: "防御性建筑，对目标造成的火焰伤害会随着时间的增加而增加。",
		getWay: "4阶竞技场，部落捐赠，商店"
	},
	{
		name: "特斯拉电磁塔",
		src: 54,
		arena: "建筑",
		rarity：: "普通",
		holyWater: "4",
		attackSpeed: "0.8秒",
		aims: "陆空兼顾",
		attackDistance: "6",
		waitTime: "1秒",
		持续时间：: "40秒",
		introduce: "防御型建筑，会给攻击范围内的敌军带来创伤。不攻击时会接地，藏到地底下。",
		getWay: "4阶竞技场，部落捐赠，商店"
	},
	{
		name: "迫击炮",
		src: 55,
		arena: "建筑",
		rarity：: "普通",
		holyWater: "4",
		attackSpeed: "3.5秒",
		aims: "地面目标",
		attackDistance: "12",
		waitTime: "5秒",
		持续时间：: "30秒",
		introduce: "",
		getWay: "6阶竞技场解锁、部落捐赠、商店随机刷新"
	},
	{
		name: "加农炮",
		src: 56,
		arena: "建筑",
		rarity：: "普通",
		holyWater: "3",
		attackSpeed: "0.8秒",
		aims: "地面目标",
		attackDistance: "6",
		waitTime: "30秒",
		持续时间：: "40秒",
		introduce: "高攻速的加农炮可以有效地消灭敌方的地面单位，通常放在防御塔后面协助防守。",
		getWay: "玩家需要达到第三区域（Barbarian Bowl），通过开宝箱获得这张加农炮。"
	},
	{
		name: "炸弹塔",
		src: 57,
		arena: "建筑",
		rarity：: "稀有",
		holyWater: "5",
		attackSpeed: "1.6秒",
		aims: "地面目标",
		attackDistance: "6.5",
		waitTime: "1秒",
		持续时间：: "40秒",
		introduce: "向炸弹塔攻击范围内的敌人投放炸弹（空中单位除外）",
		getWay: "2阶竞技场，部落捐赠，商店"
	},
	{
		name: "骷髅墓碑",
		src: 58,
		arena: "建筑",
		rarity：: "稀有",
		holyWater: "3",
		waitTime: "1秒",
		持续时间：: "60秒",
		生产速度：: "2.9秒",
		introduce: "每隔一段时间都能召唤出骷髅与敌人作战，当墓碑被破坏时，会召唤出6个骷髅士兵",
		getWay: "2阶竞技场，部落捐赠，商店购买"
	},
	{
		name: "哥布林小屋",
		src: 59,
		arena: "建筑",
		rarity：: "稀有",
		holyWater: "5",
		waitTime: "1秒",
		soldierSpeed: "4.9秒",
		持续时间：: "60秒",
		introduce: "定期召唤哥布林长矛手的小屋。",
		getWay: "1阶竞技场，商店，部落捐赠"
	},
	{
		name: "野蛮人小屋",
		src: 60,
		arena: "建筑",
		rarity：: "稀有",
		holyWater: "7",
		waitTime: "1秒",
		持续时间：: "60秒",
		生产速度：: "14秒",
		introduce: "持续时间内召唤野蛮人进攻",
		getWay: "3阶竞技场"
	},
	{
		name: "圣水收集器",
		src: 61,
		arena: "建筑",
		rarity：: "稀有",
		holyWater: "5",
		waitTime: "1秒",
		持续时间：: "70秒",
		生产速度：: "9.8秒",
		introduce: "每9.8秒多生产一个圣水！",
		getWay: "6阶竞技场解锁、商店随机刷新、部落捐卡"
	},
	{
		name: "X连弩",
		src: 62,
		arena: "建筑",
		rarity：: "史诗",
		holyWater: "6",
		attackSpeed: "0.3秒",
		aims: "地面目标",
		attackDistance: "12",
		waitTime: "3.5秒",
		持续时间：: "40秒",
		introduce: "搭建X连弩向敌方发射弓箭",
		getWay: "玩家需要达到第三区域（Barbarian Bowl），通过开宝箱获得这张X弩"
	},
	{
		name: "电击法术",
		src: 63,
		arena: "法术",
		rarity：: "普通",
		holyWater: "2",
		作用范围：: "2.5",
		持续时间：: "1",
		introduce: "电击法术在小范围内造成伤害。对皇家塔伤害有所降低。",
		getWay: "5阶竞技场，部落捐赠，商店购买"
	},
	{
		name: "镜像法术",
		src: 64,
		arena: "法术",
		rarity：: "史诗",
		holyWater: "1",
		introduce: "花费额外1滴圣水复制您用的上一张牌",
		getWay: "5阶竞技场、商店购买"
	},
	{
		name: "哥布林飞桶",
		src: 65,
		arena: "法术",
		rarity：: "史诗",
		holyWater: "3",
		aims: "地面目标",
		amount: "3",
		introduce: "在任何区域里投放三个哥布林。",
		getWay: "1阶竞技场，商店"
	},
	{
		name: "狂暴法术",
		src: 66,
		arena: "法术",
		rarity：: "史诗",
		holyWater: "3",
		作用范围：: "5",
		持续时间：: "8秒",
		introduce: "增加小兵40%的攻击速度和移动速度，同时小屋召唤小兵的速度以及部署小兵的速度也会加快。",
		getWay: "玩家需要达到第三区域（Barbarian Bowl），通过开宝箱获得这张狂暴法术。"
	},
	{
		name: "万箭齐发",
		src: 67,
		arena: "法术",
		rarity：: "普通",
		holyWater: "1",
		aims: "陆空兼顾",
		attackDistance: "4",
		作用范围：: "4",
		introduce: "弓箭射击一大片区域，区域范围内的所有敌人受到伤害，主塔受到的伤害减半。",
		getWay: "玩家需要达到第三区域（Barbarian Bowl），通过开宝箱获得这张万箭齐发。"
	},
	{
		name: "火箭",
		src: 68,
		arena: "法术",
		rarity：: "稀有",
		holyWater: "6",
		作用范围：: "2",
		introduce: "对小范围内的敌人造成巨额伤害，对主塔的伤害减半。",
		getWay: "3阶竞技场、商店购买、部落捐赠"
	},
	{
		name: "火球",
		src: 69,
		arena: "法术",
		rarity：: "稀有",
		holyWater: "4",
		aims: "陆空兼顾",
		attackDistance: "2.5",
		作用范围：: "2.5",
		introduce: "可把一小片区域烧成灰烬，造成高额伤害，对主塔的伤害减半。",
		getWay: "开宝箱获得"
	},
	{
		name: "雷电法术",
		src: 70,
		arena: "法术",
		rarity：: "史诗",
		holyWater: "6",
		aims: "陆空兼顾",
		作用范围：: "3.5",
		amount: "3",
		introduce: "对目标区域内3个小兵或建筑物造成极高的伤害，对主塔的伤害减半。",
		getWay: "1阶竞技场，商店"
	},
	{
		name: "亡灵",
		src: 71,
		arena: "部队",
		rarity：: "普通",
		holyWater: "3",
		attackSpeed: "1秒",
		aims: "陆空兼顾",
		movingSpeed: "快",
		attackDistance: "2.5",
		waitTime: "1秒",
		introduce: "召唤3只远程空战亡灵",
		getWay: "2阶竞技场，部落捐赠，商店"
	},
	{
		name: "瓦基丽武神",
		src: 72,
		arena: "部队",
		rarity：: "稀有",
		holyWater: "4",
		attackSpeed: "1.5秒",
		aims: "地面目标",
		movingSpeed: "中等",
		amount: "1",
		introduce: "召唤出近战的瓦尔基里女武神。",
		getWay: "1阶竞技场，商店，部落捐赠"
	},
	{
		name: "骷髅兵",
		src: 73,
		arena: "部队",
		rarity：: "普通",
		holyWater: "1",
		attackSpeed: "1秒",
		aims: "地面目标",
		movingSpeed: "快",
		attackDistance: "近战",
		waitTime: "1秒",
		introduce: "召唤3个近战骷髅小兵",
		getWay: "2阶竞技场，部落捐赠，商店"
	},
	{
		name: "哥布林",
		src: 74,
		arena: "部队",
		rarity：: "普通",
		holyWater: "2",
		attackSpeed: "1.1秒",
		aims: "地面目标",
		movingSpeed: "极快",
		attackDistance: "近战",
		waitTime: "1秒",
		introduce: "召唤3个近战哥布林",
		getWay: "1阶竞技场，商店，部落捐赠"
	},
	{
		name: "哥布林投矛手",
		src: 75,
		arena: "部队",
		rarity：: "普通",
		holyWater: "2",
		attackSpeed: "1.3秒",
		aims: "陆空兼顾",
		movingSpeed: "极快",
		attackDistance: "5.5",
		amount: "3",
		introduce: "召唤3只远程哥布林长矛兵",
		getWay: "1阶竞技场，商店，部落捐赠"
	},
	{
		name: "亡灵大军",
		src: 76,
		arena: "部队",
		rarity：: "普通",
		holyWater: "5",
		attackSpeed: "1秒",
		aims: "陆空兼顾",
		movingSpeed: "快",
		attackDistance: "2.5",
		waitTime: "1秒",
		introduce: "召唤出6只移动速度快、攻击速度快的空中部队",
		getWay: "4阶竞技场，部落捐赠，商店"
	},
	{
		name: "野蛮人",
		src: 77,
		arena: "部队",
		rarity：: "普通",
		holyWater: "5",
		attackSpeed: "1.5秒",
		aims: "地面目标",
		movingSpeed: "中等",
		attackDistance: "近战",
		waitTime: "1秒",
		introduce: "召唤4个近战野蛮人",
		getWay: "3阶竞技场，部落捐赠，商店"
	},
	{
		name: "戈仑石人",
		src: 78,
		arena: "部队",
		rarity：: "史诗",
		holyWater: "8",
		attackSpeed: "2.5秒",
		movingSpeed: "慢",
		waitTime: "3秒",
		introduce: "召唤出一个戈仑石人，只能攻击建筑物，当戈仑石人被破坏时，将爆炸成两个小戈仑石人并造成范围伤害。",
		getWay: "6阶竞技场解锁、商店随机刷新"
	},
	{
		name: "弓箭手",
		src: 79,
		arena: "部队",
		rarity：: "普通",
		holyWater: "3",
		attackSpeed: "1.2秒",
		aims: "陆空兼顾",
		movingSpeed: "中等",
		amount: "2",
		introduce: "召唤两个远程弓箭手",
		getWay: "新手训练营，商店中购买，部落中请求捐献弓箭手"
	},
	{
		name: "投弹兵",
		src: 80,
		arena: "部队",
		rarity：: "普通",
		holyWater: "3",
		attackSpeed: "2s",
		aims: "地面目标",
		movingSpeed: "中等",
		attackDistance: "5",
		waitTime: "1s",
		introduce: "别看这骷髅又小又脆弱，但他投掷的炸弹可会造成范围伤害，能消灭一群敌军。",
		getWay: "新手训练营、商店购买、部落捐赠"
	},
	{
		name: "骑士",
		src: 81,
		arena: "部队",
		rarity：: "普通",
		holyWater: "3",
		attackSpeed: "1.1s",
		aims: "地面目标",
		movingSpeed: "中等",
		waitTime: "1s",
		introduce: "一位强悍的近战勇士。他是野蛮人的远亲，但是更英俊更有教养。传言说，他仅因为那拉风的胡须就受封骑士了。",
		getWay: "新手训练营、商店购买、部落捐赠"
		//数量 攻击距离 持续时间
		//amount attackDistance
	}
]